// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbIk-mr_4KCWfFQqpzNqOjUU3TzZnLmaQ',
    appId: '1:741193296693:web:e82f934250fdc777937a7c',
    messagingSenderId: '741193296693',
    projectId: 'e-commece-flutter',
    authDomain: 'e-commece-flutter.firebaseapp.com',
    storageBucket: 'e-commece-flutter.firebasestorage.app',
    measurementId: 'G-YS6LF1L0RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqbDjrupiWBro00NeodxDFA6jTuvomejc',
    appId: '1:741193296693:android:09abfd4ac25a2a22937a7c',
    messagingSenderId: '741193296693',
    projectId: 'e-commece-flutter',
    storageBucket: 'e-commece-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcCCf4XNcWQXwJVCU0NbVOnl_CQvQKiPw',
    appId: '1:741193296693:ios:7d2405350539ce34937a7c',
    messagingSenderId: '741193296693',
    projectId: 'e-commece-flutter',
    storageBucket: 'e-commece-flutter.firebasestorage.app',
    iosBundleId: 'com.example.eCommece',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcCCf4XNcWQXwJVCU0NbVOnl_CQvQKiPw',
    appId: '1:741193296693:ios:7d2405350539ce34937a7c',
    messagingSenderId: '741193296693',
    projectId: 'e-commece-flutter',
    storageBucket: 'e-commece-flutter.firebasestorage.app',
    iosBundleId: 'com.example.eCommece',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbIk-mr_4KCWfFQqpzNqOjUU3TzZnLmaQ',
    appId: '1:741193296693:web:e2b3c5837fabb0b8937a7c',
    messagingSenderId: '741193296693',
    projectId: 'e-commece-flutter',
    authDomain: 'e-commece-flutter.firebaseapp.com',
    storageBucket: 'e-commece-flutter.firebasestorage.app',
    measurementId: 'G-FE7RNLWKLW',
  );

}